"
" See colors/mhb_colors for documentation
let macvim_skip_colorscheme=1
let g:colors_name = "mhb_colors"
colorscheme mhb_colors

" Skip commands that clash with Explore
delcommand Educate
delcommand NoEducate
delcommand ToggleEducate
delcommand Emmet
delcommand EmmetInstall

" Insteady use after/syntax/markdown.vim with
" syntax clear markdownError
" Fix up Markdown error detection for _
" syn match markdownError "\w\@<=\w\@="
