" set background=light
colorscheme solarized8
hi NonText ctermfg=7 guifg=gray
hi SpecialKey ctermfg=7 guifg=gray
" se antialias

delcommand Educate
delcommand NoEducate
delcommand ToggleEducate

"colorscheme solarized8_light_high

"call FixColors()
